# Generated by Django 3.0.1 on 2019-12-27 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=10)),
                ('mail', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=50)),
                ('movie_id', models.CharField(max_length=70, unique=True)),
            ],
            options={
                'db_table': 'movies',
            },
        ),
        migrations.CreateModel(
            name='Movie_Verdict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verdict_link', models.CharField(max_length=500)),
                ('comment', models.TextField()),
                ('rating', models.CharField(max_length=10)),
                ('movie', models.ForeignKey(db_column='movie_id', on_delete=django.db.models.deletion.CASCADE, related_name='movie_verdict', to='onemovie.Movies', to_field='movie_id')),
            ],
            options={
                'db_table': 'movie_verdict_info',
            },
        ),
        migrations.CreateModel(
            name='Movie_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_info', models.TextField()),
                ('image_name', models.CharField(max_length=200)),
                ('movie', models.OneToOneField(db_column='movie_id', on_delete=django.db.models.deletion.CASCADE, related_name='movie', to='onemovie.Movies', to_field='movie_id')),
            ],
            options={
                'db_table': 'movie_info',
            },
        ),
    ]
