# Generated by Django 3.0.1 on 2019-12-27 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onemovie', '0002_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='user',
            field=models.IntegerField(),
        ),
    ]
